"use client";
import { useEffect, useState, useCallback } from "react";
import { FOLLOWUP_FIELDS } from "@/config/selection-followup";
import TrainingHint from "@/components/training/TrainingHint";
const followupHelp: Record<string, string> = {
  referido: "Indica si la persona llegó recomendada por alguien. Si eliges Sí, registra quién la refiere.",
  referidoPor: "Escribe nombre y apellido de la persona que hizo la recomendación.",
  pretelefonica: "Resume la llamada inicial: fecha, responsable, disponibilidad y puntos relevantes.",
  pruebas: "Enumera las pruebas aplicadas y cuándo se realizaron.",
  resultados: "Registra los resultados concretos de las pruebas, evitando conclusiones sin evidencia.",
  perfil: "Explica cómo el perfil cumple o no los requisitos de la vacante.",
  referencias: "Documenta las referencias consultadas y su resultado.",
  observaciones: "Deja notas internas útiles para la siguiente persona que revise el proceso.",
  decision: "Explica el motivo de la decisión final con lenguaje claro y respetuoso.",
  traslado: "Registra por qué se consideró otra vacante y la gestión de notificación por llamada.",
};
type Interview={id:string;fecha:string;modalidad:string;duracion:number;lugar:string;enlace:string;estado:string;resultado:string;observaciones:string;entrevistador_nombre:string};
type Data={profile:Record<string,string>;fields:Record<string,string>;revision:number;steps:string[];canEdit:boolean;history:{descripcion:string;created_at:string}[];interviews:Interview[]};
export default function ApplicationFollowup({id}:{id:string}){
  const [data,setData]=useState<Data|null>(null),[fields,setFields]=useState<Record<string,string>>({}),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{try{const response=await fetch(`${process.env.NEXT_PUBLIC_TRAINING_BASE_PATH || ""}/api/vacantes/postulaciones/${id}/seguimiento`,{cache:"no-store"});const result=await response.json();if(!response.ok)throw new Error(result.message);setData(result);setFields(result.fields);}catch(e){setMessage(e instanceof Error?e.message:"No fue posible cargar.");}},[id]);
  useEffect(()=>{void load();},[load]);
  const [interviewDate,setInterviewDate]=useState(""),[mode,setMode]=useState("Presencial"),[duration,setDuration]=useState("60"),[interviewState,setInterviewState]=useState("Programada"),[result,setResult]=useState("Pendiente"),[place,setPlace]=useState(""),[link,setLink]=useState(""),[interviewNotes,setInterviewNotes]=useState("");
  async function addInterview(){
    if(!interviewDate||!interviewNotes.trim()){setMessage("Completa la fecha y la observación de la entrevista.");return;}
    setBusy(true);setMessage("");
    try{
      const response=await fetch(`${process.env.NEXT_PUBLIC_TRAINING_BASE_PATH || ""}/api/vacantes/postulaciones/${id}/seguimiento`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({date:interviewDate,modality:mode,duration:Number(duration),state:interviewState,result,place,link,notes:interviewNotes})});
      const responseData=await response.json();if(!response.ok)throw new Error(responseData.message||"No fue posible registrar la entrevista.");
      setInterviewDate("");setDuration("60");setInterviewState("Programada");setResult("Pendiente");setPlace("");setLink("");setInterviewNotes("");await load();setMessage("Entrevista registrada y añadida a la trazabilidad.");
    }catch(error){setMessage(error instanceof Error?error.message:"No fue posible registrar la entrevista.");}finally{setBusy(false);}
  }
  async function save(){
    if(!data||busy)return;
    setBusy(true);setMessage("");
    try{const response=await fetch(`${process.env.NEXT_PUBLIC_TRAINING_BASE_PATH || ""}/api/vacantes/postulaciones/${id}/seguimiento`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({fields,revision:data.revision})});const result=await response.json();if(!response.ok)throw new Error(result.message);await load();setMessage("Ficha guardada. Los cambios quedaron en el historial y la auditoría.");}catch(e){setMessage(e instanceof Error?e.message:"No fue posible guardar.");}finally{setBusy(false);}
  }
  return <section className="col-span-full mt-6 rounded-2xl border border-blue-200 bg-white p-5">
    <h3 className="text-lg font-bold text-primary">Ficha de seguimiento de esta postulación</h3>
    <p className="mt-1 text-sm text-textLight">Datos del perfil precargados y evaluación interna del proceso.</p>
    <p role="status" className="my-3 text-sm">{message}</p>
    {data?<><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{Object.entries({nombres:"Nombres",apellidos:"Apellidos",documento:"Cédula",telefono:"Teléfono",email:"Correo",direccion:"Dirección",ciudad:"Ciudad",departamento:"Departamento",profesion:"Título o profesión",educacion:"Nivel académico",experiencia:"Experiencia"}).map(([key,label])=><div key={key} className="rounded-lg bg-slate-50 p-3 text-sm"><p className="font-semibold text-textLight">{label}</p><p className="whitespace-pre-wrap break-words">{data.profile[key]||"No registrado"}</p></div>)}</div>
    {data.profile.observaciones_rh&&<div className="my-4 rounded-lg bg-violet-50 p-3"><h4 className="font-bold">Notas y traslados anteriores</h4><p className="whitespace-pre-wrap text-sm">{data.profile.observaciones_rh}</p></div>}
    <div className="mt-5 grid gap-4 sm:grid-cols-2">{Object.entries(FOLLOWUP_FIELDS).filter(([key])=>!['entrevista','entrevistadores'].includes(key)).map(([key,label])=><TrainingHint key={key} text={followupHelp[key] || `Completa ${label.toLowerCase()} con información verificada del proceso.`}><label className="block text-sm font-semibold">{label}{data.steps.includes(key)&&<span className="ml-2 text-xs text-blue-700">Previsto en la vacante</span>}{key==="referido"?<select disabled={!data.canEdit||busy} value={fields[key]??""} onChange={e=>setFields({...fields,[key]:e.target.value})} className="mt-2 block w-full rounded-xl border p-3"><option value="">Sin registrar</option><option value="Sí">Sí</option><option value="No">No</option></select>:<textarea disabled={!data.canEdit||busy} value={fields[key]??""} maxLength={10000} rows={4} onChange={e=>setFields({...fields,[key]:e.target.value})} className="mt-2 w-full rounded-xl border border-border p-3 font-normal disabled:bg-slate-50"/>}</label></TrainingHint>)}</div>
    <section className="mt-6 rounded-2xl border border-violet-200 bg-violet-50/50 p-4"><div className="flex items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-violet-700">Historial de entrevistas</p><h4 className="mt-1 font-bold text-text">{data.interviews?.length||0} entrevista(s) registrada(s)</h4></div></div>
      <div className="mt-4 grid gap-3">{data.interviews?.map(interview=><TrainingHint key={interview.id} text="Entrevista registrada con su fecha, modalidad, responsable, resultado y observación. Queda en la trazabilidad de esta postulación."><article className="rounded-xl border border-violet-100 bg-white p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-bold text-text">{new Date(interview.fecha).toLocaleString('es-CO')}</p><p className="mt-1 text-xs text-textLight">{interview.modalidad} · {interview.duracion} minutos · {interview.entrevistador_nombre}</p></div><div className="flex gap-2"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold text-slate-700">{interview.estado}</span><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${interview.resultado==='Aprobado'?'bg-emerald-100 text-emerald-700':interview.resultado==='Rechazado'?'bg-red-100 text-red-700':'bg-amber-100 text-amber-800'}`}>{interview.resultado}</span></div></div><p className="mt-3 whitespace-pre-wrap text-sm text-text">{interview.observaciones}</p>{(interview.lugar||interview.enlace)&&<p className="mt-2 break-all text-xs text-primary">{interview.lugar||interview.enlace}</p>}</article></TrainingHint>)}{!data.interviews?.length&&<p className="rounded-xl border border-dashed border-violet-200 bg-white p-5 text-center text-sm text-textLight">Aún no hay entrevistas estructuradas para esta postulación.</p>}</div>
    </section>
    {data.canEdit&&<fieldset className="mt-5 rounded-2xl border border-violet-200 bg-white p-4"><legend className="px-2 font-bold text-violet-800">Agregar otra entrevista</legend>
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
        <TrainingHint text="Fecha y hora acordadas para la entrevista; son obligatorias para registrar este movimiento."><label className="block text-sm font-semibold">Fecha y hora<input type="datetime-local" value={interviewDate} onChange={e=>setInterviewDate(e.target.value)} className="mt-1 w-full rounded-lg border p-2.5"/></label></TrainingHint>
        <TrainingHint text="Selecciona si la entrevista será presencial, por llamada o mediante una plataforma virtual."><label className="block text-sm font-semibold">Modalidad<select value={mode} onChange={e=>setMode(e.target.value)} className="mt-1 w-full rounded-lg border p-2.5"><option>Presencial</option><option>Google Meet</option><option>Microsoft Teams</option><option>Zoom</option><option>Llamada Telefónica</option></select></label></TrainingHint>
        <TrainingHint text="Duración prevista o realizada, entre 15 y 480 minutos."><label className="block text-sm font-semibold">Duración (minutos)<input type="number" min={15} max={480} step={15} value={duration} onChange={e=>setDuration(e.target.value)} className="mt-1 w-full rounded-lg border p-2.5"/></label></TrainingHint>
        <TrainingHint text="Indica si está programada, realizada, cancelada o reagendada."><label className="block text-sm font-semibold">Estado<select value={interviewState} onChange={e=>setInterviewState(e.target.value)} className="mt-1 w-full rounded-lg border p-2.5"><option>Programada</option><option>Realizada</option><option>Cancelada</option><option>Reagendada</option></select></label></TrainingHint>
        <TrainingHint text="Registra el resultado de la evaluación. Si aún no se ha realizado, deja Pendiente."><label className="block text-sm font-semibold">Resultado<select value={result} onChange={e=>setResult(e.target.value)} className="mt-1 w-full rounded-lg border p-2.5"><option>Pendiente</option><option>Aprobado</option><option>Rechazado</option></select></label></TrainingHint>
        {mode==='Presencial'?<TrainingHint text="Lugar físico donde se realizará la entrevista."><label className="block text-sm font-semibold">Lugar<input value={place} onChange={e=>setPlace(e.target.value)} maxLength={255} className="mt-1 w-full rounded-lg border p-2.5"/></label></TrainingHint>:mode!=='Llamada Telefónica'?<TrainingHint text="Pega la URL de la reunión virtual con formato https://."><label className="block text-sm font-semibold">Enlace de conexión<input type="url" value={link} onChange={e=>setLink(e.target.value)} maxLength={255} placeholder="https://" className="mt-1 w-full rounded-lg border p-2.5"/></label></TrainingHint>:null}
      </div>
      <TrainingHint text="Describe lo conversado, la conclusión y el siguiente paso. La observación es obligatoria y queda asociada a esta entrevista."><label className="mt-3 block text-sm font-semibold">Observación y conclusión<textarea placeholder="Registra el desarrollo, conclusión y siguiente acción..." value={interviewNotes} maxLength={5000} rows={4} onChange={e=>setInterviewNotes(e.target.value)} className="mt-1 w-full rounded-lg border p-3"/></label></TrainingHint>
      <TrainingHint text="Guarda una entrevista nueva sin reemplazar las anteriores. Revisa fecha y observación antes de registrarla."><button type="button" disabled={busy||!interviewDate||!interviewNotes.trim()} onClick={()=>void addInterview()} className="mt-3 rounded-xl bg-violet-700 px-4 py-3 font-bold text-white disabled:opacity-50">{busy?'Guardando...':'Registrar entrevista'}</button></TrainingHint>
    </fieldset>}
    {data.canEdit&&<TrainingHint text="Guarda las respuestas de la ficha de seguimiento. El historial y la auditoría conservarán los cambios."><button type="button" disabled={busy} onClick={()=>void save()} className="mt-4 rounded-xl bg-primary px-5 py-3 font-bold text-white disabled:opacity-50">{busy?"Guardando...":"Guardar ficha y observaciones"}</button></TrainingHint>}
    <details className="mt-5"><summary className="cursor-pointer font-bold text-primary">Historial de edición ({data.history.length})</summary>{data.history.map((entry,index)=><div key={index} className="mt-3 rounded-lg border p-3 text-sm"><p className="text-textLight">{new Date(entry.created_at).toLocaleString("es-CO")}</p><p className="whitespace-pre-wrap">{entry.descripcion}</p></div>)}</details></>:!message&&<p className="py-4 text-sm">Cargando ficha...</p>}
  </section>;
}
