"use client";
import {useState} from "react";
const labels:Record<string,string>={nombre:"Nombre completo",documento:"Cédula",correo:"Correo",telefono:"Teléfono",ciudad:"Ciudad",departamento:"Departamento",vacante:"Cargo",estado:"Estado",observaciones:"Observaciones",evaluacion:"Evaluación y pruebas",motivo_descarte:"Motivo de decisión",licencia_runt:"Licencia / RUNT"};
export default function HistoricalEdit({id,onSaved}:{id:number;onSaved:()=>void}){
  const [record,setRecord]=useState<Record<string,string>|null>(null),[raw,setRaw]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  async function open(){setBusy(true);try{const response=await fetch(`/api/vacantes/historial-hv/editar?id=${id}`);const result=await response.json();if(!response.ok)throw new Error(result.message);setRecord(Object.fromEntries(Object.keys(labels).map(key=>[key,String(result[key]??"")])));const data=typeof result.raw_data==="string"?JSON.parse(result.raw_data||"{}"):result.raw_data||{};setRaw(Object.fromEntries(Object.entries(data).map(([key,value])=>[key,String(value??"")])));}catch(e){setMessage(e instanceof Error?e.message:"No fue posible cargar.");}finally{setBusy(false);}}
  async function save(){setBusy(true);try{const response=await fetch("/api/vacantes/historial-hv/editar",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({...record,id,raw_data:JSON.stringify(raw)})});const result=await response.json();if(!response.ok)throw new Error(result.message);setMessage("Datos guardados y cambios auditados.");onSaved();setRecord(null);}catch(e){setMessage(e instanceof Error?e.message:"No fue posible guardar.");}finally{setBusy(false);}}
  return <section className="my-4 rounded-xl border bg-white p-4"><button type="button" disabled={busy} onClick={()=>void open()} className="rounded-lg bg-primary px-4 py-2 text-white">Editar datos del histórico</button><p role="status" className="my-2 text-sm">{message}</p>{record&&<><p className="my-3 text-sm">Los datos personales se actualizarán en los registros de esta persona. Las notas pertenecen a este movimiento.</p><div className="grid gap-3 sm:grid-cols-2">{Object.entries(labels).map(([key,label])=><label key={key} className="text-sm">{label}<textarea value={record[key]} onChange={e=>setRecord({...record,[key]:e.target.value})} className="mt-1 w-full rounded-lg border p-2"/></label>)}</div><h4 className="my-3 font-bold">Campos del Excel</h4>{Object.entries(raw).filter(([key])=>key!=="_Edición interna").map(([key,value])=><label key={key} className="my-3 block text-sm">{key}<textarea value={value} onChange={e=>setRaw({...raw,[key]:e.target.value})} className="mt-1 w-full rounded-lg border p-2"/></label>)}<button type="button" onClick={()=>setRaw({...raw,[`Entrevista presencial o virtual ${Object.keys(raw).filter(key=>key.startsWith("Entrevista presencial o virtual")).length+1}`]:""})} className="mr-3 rounded-lg border p-2">Agregar entrevista</button><button type="button" disabled={busy} onClick={()=>void save()} className="rounded-lg bg-emerald-700 p-3 text-white">{busy?"Guardando...":"Guardar cambios"}</button></>}</section>;
}
