"use client";
import { useState } from "react";
import TrainingHint from "@/components/training/TrainingHint";
export default function SelectionReport(){
  const [from,setFrom]=useState(""),[to,setTo]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
  async function download(){if(from&&to&&from>to){setError("La fecha inicial no puede ser posterior a la fecha final.");return;}setBusy(true);setError("");try{const params=new URLSearchParams();if(from)params.set("from",from);if(to)params.set("to",to);const response=await fetch(`/api/vacantes/reporte-seleccion?${params}`,{cache:"no-store"});if(!response.ok)throw new Error((await response.json()).message);const url=URL.createObjectURL(await response.blob()),link=document.createElement("a");link.href=url;link.download=`reporte-seleccion-${from||"inicio"}-${to||"actual"}.xlsx`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e instanceof Error?e.message:"No fue posible descargar.");}finally{setBusy(false);}}
  return <section className="my-5 rounded-2xl border border-blue-100 bg-white p-5 shadow-sm">
    <div className="flex flex-wrap items-start justify-between gap-3"><TrainingHint text="Este reporte reúne seis hojas: resumen, trazabilidad, postulaciones, entrevistas, historial laboral y auditoría. Los colores muestran el estado de cada proceso."><div><p className="text-xs font-bold uppercase tracking-wider text-primary">Reporte consolidado</p><h3 className="mt-1 text-lg font-bold text-text">Excel de selección y trazabilidad</h3><p className="mt-1 max-w-3xl text-sm text-textLight">Incluye en un solo archivo el resumen, la trazabilidad completa, postulaciones, entrevistas, historial laboral y auditoría. Cada hoja conserva sus fechas y semáforos visuales.</p></div></TrainingHint><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-700">6 hojas integradas</span></div>
    <div className="mt-4 flex flex-wrap items-end gap-3 rounded-xl bg-slate-50 p-4">
      <TrainingHint text="Fecha inicial para incluir registros en el Excel. Si la dejas vacía, el reporte parte desde el inicio."><label className="block text-sm font-semibold text-text">Desde<input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="mt-1 block rounded-lg border border-border bg-white p-2.5 font-normal"/></label></TrainingHint>
      <TrainingHint text="Fecha final del reporte. Debe ser igual o posterior a la fecha inicial."><label className="block text-sm font-semibold text-text">Hasta<input type="date" min={from||undefined} value={to} onChange={e=>setTo(e.target.value)} className="mt-1 block rounded-lg border border-border bg-white p-2.5 font-normal"/></label></TrainingHint>
      <TrainingHint text="Genera un Excel con las seis hojas integradas y el período seleccionado. Comprueba las fechas antes de descargar."><button type="button" disabled={busy} onClick={()=>void download()} className="min-h-11 rounded-lg bg-primary px-5 py-2.5 font-bold text-white shadow-sm disabled:opacity-50">{busy?"Generando archivo...":"Descargar Excel completo"}</button></TrainingHint>
      {(from||to)&&<TrainingHint text="Borra el rango de fechas para volver a incluir todo el período disponible."><button type="button" disabled={busy} onClick={()=>{setFrom("");setTo("");setError("");}} className="min-h-11 rounded-lg border border-border bg-white px-4 py-2.5 font-semibold text-primary">Limpiar fechas</button></TrainingHint>}
    </div>
    <p role="status" className="mt-2 min-h-5 text-sm font-medium text-red-700">{error}</p>
  </section>;
}
