/**
 * Planes - Jardines del Renacer
 * Configuracion de todos los planes disponibles
 */

export const PLANS_CONFIG = {
  'tranquilidad-total': {
    id: 'tranquilidad-total',
    planType: 'Individual',
    name: 'Plan tranquilidad total',
    tagline: 'Proteccion individual y prevision anticipada',
    description:
      'Disenado para personas independientes que desean dejar todo previsto y evitar cargas a sus seres queridos.',
    includes: 'Servicio funerario integral, acompanamiento familiar, gestion documental',
    price: 'Cotizar ahora',
    geographicCoverage: 'Nacional',
    conditions: 'Aplica para titular',
    image: '/images/individual_plan.webp',
    featured: true,
    benefits: [
      'Proteccion individual',
      'Prevision anticipada',
      'Evita gastos inesperados',
      'Tranquilidad absoluta',
      'Cobertura nacional',
      'Parque automotor',
      'Asesoria juridica',
      'Ayudas de duelo',
      'Beneficios plus',
    ],
  },
  'proteccion-familiar-esencial': {
    id: 'proteccion-familiar-esencial',
    planType: 'Familiar',
    name: 'Plan familiar esencial',
    tagline: 'El plan mas adquirido para proteger tu nucleo familiar',
    description:
      'Plan mas adquirido, disenado para proteger al nucleo familiar con cobertura integral.',
    includes:
      'Cobertura para titular y grupo familiar, incluyendo adultos mayores hasta 85 anos en primer grado',
    price: 'Cotizar ahora',
    geographicCoverage: 'Nacional',
    conditions: 'Incluye hasta 2 adultos mayores',
    image: '/images/familiar_plan.webp',
    featured: true,
    benefits: [
      'Economia familiar',
      'Cobertura amplia',
      'Respaldo inmediato',
      'Proteccion multigeneracional',
      'Cobertura nacional',
      'Parque automotor',
      'Asesoria juridica',
      'Ayudas de duelo',
      'Beneficios plus',
    ],
  },
  celestial: {
    id: 'celestial',
    planType: 'Segmentado',
    name: 'Plan celestial',
    tagline: 'Acompanamiento respetuoso para comunidades cristianas',
    description:
      'Orientado a comunidades cristianas, respetando rituales y creencias religiosas.',
    includes:
      'Servicio funerario con acompanamiento espiritual, coordinacion con iglesia',
    price: 'Cotizar ahora',
    geographicCoverage: 'Nacional',
    conditions: 'Requiere validacion de iglesia',
    image: '/images/celestial_plan.jpg',
    featured: false,
    benefits: [
      'Respeto por la fe',
      'Acompanamiento religioso',
      'Conexion espiritual en el proceso',
      'Cobertura nacional',
      'Parque automotor',
      'Asesoria juridica',
      'Ayudas de duelo',
      'Beneficios plus',
    ],
  },
  'aliado-tendero': {
    id: 'aliado-tendero',
    planType: 'Segmentado',
    name: 'Plan aliado tendero',
    tagline: 'Beneficios economicos y comerciales para tenderos',
    description:
      'Disenado para tenderos del pais, con beneficios economicos y acompanamiento comercial.',
    includes: 'Cobertura funeraria + beneficios comerciales',
    price: 'Cotizar ahora',
    geographicCoverage: 'Nacional',
    conditions: 'Requiere camara de comercio y validacion del negocio',
    image: '/images/tendero_plan.jpg',
    featured: false,
    benefits: [
      'Tarifas preferenciales',
      'Acompanamiento al negocio',
      'Beneficios exclusivos del gremio',
      'Cobertura nacional',
      'Parque automotor',
      'Asesoria juridica',
      'Ayudas de duelo',
      'Beneficios plus',
    ],
  },
  'comunidad-activa': {
    id: 'comunidad-activa',
    planType: 'Segmentado',
    name: 'Plan comunidad activa',
    tagline: 'Proteccion colectiva para juntas de accion comunal',
    description:
      'Dirigido a miembros de juntas de accion comunal, fortaleciendo el bienestar colectivo.',
    includes: 'Cobertura funeraria para afiliados',
    price: 'Cotizar ahora',
    geographicCoverage: 'Nacional',
    conditions: 'Aplica para miembros activos de juntas',
    image: '/images/comunidad_plan.webp',
    featured: false,
    benefits: [
      'Tarifas especiales',
      'Enfoque comunitario',
      'Acceso colectivo a beneficios',
      'Cobertura nacional',
      'Parque automotor',
      'Asesoria juridica',
      'Ayudas de duelo',
      'Beneficios plus',
    ],
  },
  'vocacion-docente': {
    id: 'vocacion-docente',
    planType: 'Segmentado',
    name: 'Plan vocacion docente',
    tagline: 'Respaldo para educadores y sus familias',
    description: 'Disenado para educadores, reconociendo su labor y estabilidad.',
    includes: 'Cobertura familiar + beneficios adicionales',
    price: 'Cotizar ahora',
    geographicCoverage: 'Nacional',
    conditions: 'Validacion como docente',
    image: '/images/docente_plan.webp',
    featured: false,
    benefits: [
      'Tarifas preferenciales',
      'Estabilidad financiera',
      'Proteccion familiar para docentes',
      'Cobertura nacional',
      'Parque automotor',
      'Asesoria juridica',
      'Ayudas de duelo',
      'Beneficios plus',
    ],
  },
  'heroes-nacion': {
    id: 'heroes-nacion',
    planType: 'Segmentado',
    name: 'Plan heroes de la nación',
    tagline: 'Beneficios exclusivos para fuerza publica',
    description: 'Dirigido a fuerza publica, policia e INPEC, en reconocimiento a su servicio.',
    includes: 'Cobertura integral familiar',
    price: 'Cotizar ahora',
    geographicCoverage: 'Nacional',
    conditions: 'Validacion institucional',
    image: '/images/Heroes_plan.jpg',
    featured: false,
    benefits: [
      'Beneficios exclusivos',
      'Respaldo institucional',
      'Proteccion prioritaria',
      'Cobertura nacional',
      'Parque automotor',
      'Asesoria juridica',
      'Ayudas de duelo',
      'Beneficios plus',
    ],
  },
  'prevision-inmediata': {
    id: 'prevision-inmediata',
    planType: 'Especial',
    name: 'Plan prevision inmediata',
    tagline: 'Solucion inmediata con pago anticipado',
    description:
      'Alternativa para quienes no pueden adquirir prevision tradicional o prefieren pago anticipado.',
    includes: 'Titulo funerario unipersonal, universal o mascotas',
    price: 'Cotizar ahora',
    geographicCoverage: 'Nacional',
    conditions: 'Pago anticipado',
    image: '/images/plan_prevision_inmediata.webp',
    featured: true,
    benefits: [
      'Acceso sin restricciones de edad',
      'Solucion inmediata',
      'Flexibilidad',
      'Cobertura nacional',
      'Parque automotor',
      'Asesoria juridica',
    ],
  },
  'bienestar-empresarial': {
    id: 'bienestar-empresarial',
    planType: 'Corporativo',
    name: 'Plan empresarial',
    tagline: 'Beneficio empresarial para colaboradores',
    description: 'Disenado para empresas que desean proteger a sus colaboradores.',
    includes: 'Cobertura para empleados via nomina',
    price: 'Cotizar ahora',
    geographicCoverage: 'Nacional',
    conditions: 'Convenio empresarial',
    image: '/images/empresarial_plan.jpg',
    featured: false,
    benefits: [
      'Fidelizacion del talento',
      'Beneficio empresarial',
      'Tarifas preferenciales',
      'Cobertura nacional',
      'Parque automotor',
      'Asesoria juridica',
      'Ayudas de duelo',
      'Beneficios plus',
    ],
  },
  'profesional-independiente': {
    id: 'profesional-independiente',
    planType: 'Independientes',
    name: 'Plan independiente',
    tagline: 'Proteccion autonoma para profesionales independientes',
    description:
      'Dirigido a profesionales independientes que buscan proteccion sin depender de una empresa.',
    includes: 'Cobertura individual o familiar',
    price: 'Cotizar ahora',
    geographicCoverage: 'Nacional',
    conditions: 'Validacion profesional',
    image: '/images/profesional_independiente_plan.jpg',
    featured: false,
    benefits: [
      'Flexibilidad',
      'Respaldo financiero',
      'Proteccion autonoma',
      'Cobertura nacional',
      'Parque automotor',
      'Asesoria juridica',
      'Ayudas de duelo',
      'Beneficios plus',
    ],
  },
} as const;

export type PlanId = keyof typeof PLANS_CONFIG;
