"use client";

import { useEffect, useCallback, useRef, useState } from "react";
import { Download, FileUp, History, Search, ShieldCheck, UserRound } from "lucide-react";
import ConfirmDialog from "@/components/ui/ConfirmDialog";
import HistoricalRecordActions from "@/components/vacantes/HistoricalRecordActions";
import ScreenDialog from "@/components/ui/ScreenDialog";
import TrainingHint from "@/components/training/TrainingHint";

type Item = { id:number; name:string; documentNumber:string; email:string; phone:string; city:string; department:string; processDate:string|null; vacancyTitle:string; status:string; source:string; interviewers:string; observations:string; evaluation:string; discardReason:string; licenseCheck:string; rawData:string; sourceSheet:string; sourceRow:number };
const tones: Record<string,string> = { Seleccionado:"border-emerald-200 bg-emerald-50 text-emerald-700", Trasladado:"border-violet-200 bg-violet-50 text-violet-700", Recibida:"border-sky-200 bg-sky-50 text-sky-700", Contratado:"border-emerald-200 bg-emerald-50 text-emerald-700", "No continúa":"border-red-200 bg-red-50 text-red-700", Entrevista:"border-violet-200 bg-violet-50 text-violet-700", "Prueba técnica":"border-orange-200 bg-orange-50 text-orange-700", "En revisión":"border-amber-200 bg-amber-50 text-amber-800" };

export default function HistoricalWorkPage() {
  const [items,setItems]=useState<Item[]>([]), [totals,setTotals]=useState({candidates:0,movements:0}), [query,setQuery]=useState(""), [status,setStatus]=useState(""), [from,setFrom]=useState(""), [to,setTo]=useState(""), [file,setFile]=useState<File|null>(null), [loading,setLoading]=useState(true), [importing,setImporting]=useState(false), [exporting,setExporting]=useState(false), [selected,setSelected]=useState<Item|null>(null), [notice,setNotice]=useState<{title:string;description:string;variant:"success"|"error"}|null>(null);
  const [confirmClear,setConfirmClear]=useState(false), [clearing,setClearing]=useState(false), [clearPassword,setClearPassword]=useState("");
  const [page,setPage]=useState(1), [pageSize,setPageSize]=useState(10);
  const [pagination,setPagination]=useState({page:1,pageSize:10,total:0,totalPages:1});
  const [statuses,setStatuses]=useState<string[]>([]);
  useEffect(()=>{const value=new URLSearchParams(window.location.search).get("q");if(value)setQuery(value);},[]);
  const requestNumber=useRef(0);
  const load=useCallback(async()=>{
    const current=++requestNumber.current;
    setLoading(true);
    try {
      const params=new URLSearchParams({page:String(page),pageSize:String(pageSize)});
      if(query.trim())params.set("q",query.trim());
      if(status)params.set("status",status);
      if(from)params.set("from",from);
      if(to)params.set("to",to);
      const response=await fetch(`/api/vacantes/historial-hv?${params}`,{cache:"no-store"});
      const result=await response.json();
      if(current!==requestNumber.current)return;
      if(!response.ok||!result.success)throw new Error(result.message||"No fue posible consultar el historial.");
      setItems(result.data||[]);
      setTotals(result.totals||{candidates:0,movements:0});
      setPagination(result.pagination);
      setStatuses(result.statuses||[]);
    } catch(error) {
      if(current===requestNumber.current)setNotice({title:"No fue posible cargar",description:error instanceof Error?error.message:"Intenta nuevamente.",variant:"error"});
    } finally {if(current===requestNumber.current)setLoading(false);}
  },[page,pageSize,query,status,from,to]);
  useEffect(()=>{
    const requestCounter=requestNumber;
    const timer=setTimeout(()=>void load(),300);
    return ()=>{clearTimeout(timer);requestCounter.current++;};
  },[load]);
  const upload=async()=>{if(!file)return;setImporting(true);try{const f=new FormData();f.append("file",file);const r=await fetch("/api/vacantes/historial-hv/import",{method:"POST",body:f}),v=await r.json();if(!r.ok||!v.success)throw new Error(v.message||"No fue posible importar.");setNotice({title:"Historial importado",description:`Se analizaron ${v.data.analyzedRows} filas y se agregaron ${v.data.importedMovements} movimientos nuevos.`,variant:"success"});setFile(null);await load();}catch(e){setNotice({title:"Importación no realizada",description:e instanceof Error?e.message:"Intenta nuevamente.",variant:"error"});}finally{setImporting(false);}};
  const downloadReport=async()=>{if(from&&to&&from>to){setNotice({title:"Rango de fechas inválido",description:"La fecha inicial no puede ser posterior a la fecha final.",variant:"error"});return;}setExporting(true);try{const params=new URLSearchParams();if(from)params.set("from",from);if(to)params.set("to",to);const response=await fetch(`/api/vacantes/reporte-seleccion?${params}`,{cache:"no-store"});if(!response.ok){const result=await response.json().catch(()=>({}));throw new Error(result.message||"No fue posible generar el Excel.");}const url=URL.createObjectURL(await response.blob()),link=document.createElement("a");link.href=url;link.download=`reporte-seleccion-${from||"inicio"}-${to||"actual"}.xlsx`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setNotice({title:"Excel no generado",description:e instanceof Error?e.message:"Intenta nuevamente.",variant:"error"});}finally{setExporting(false);}};
  const clearHistory=async()=>{if(!clearPassword)return;setClearing(true);try{const r=await fetch("/api/vacantes/historial-hv",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:clearPassword})}),v=await r.json();if(!r.ok||!v.success)throw new Error(v.message||"No fue posible eliminar el historial.");setItems([]);setPagination({page:1,pageSize,total:0,totalPages:1});setPage(1);setTotals({candidates:0,movements:0});setConfirmClear(false);setClearPassword("");setNotice({title:"Historial eliminado",description:`Se eliminaron ${v.data.deletedMovements} movimientos importados y ${v.data.deletedCandidates} candidatos históricos.`,variant:"success"});}catch(e){setNotice({title:"Eliminación no realizada",description:e instanceof Error?e.message:"Intenta nuevamente.",variant:"error"});}finally{setClearing(false);}};
  return <div className="space-y-6 p-5 md:p-8"><ConfirmDialog open={!!notice} title={notice?.title??""} description={notice?.description??""} confirmLabel="Entendido" showCancel={false} variant={notice?.variant} onConfirm={()=>setNotice(null)} onCancel={()=>setNotice(null)}/>
    <ConfirmDialog open={confirmClear} title="Eliminar historial importado" description="Confirma con tu contraseña. Se eliminarán únicamente los registros cargados desde el Excel histórico; las vacantes y postulantes actuales no se verán afectados." confirmLabel={clearing?"Eliminando...":"Eliminar historial"} variant="danger" onConfirm={()=>void clearHistory()} onCancel={()=>{setConfirmClear(false);setClearPassword("");}}><input type="password" autoFocus value={clearPassword} onChange={e=>setClearPassword(e.target.value)} placeholder="Contraseña del administrador" className="w-full rounded-xl border border-[#b4c7df] bg-white px-4 py-3 text-sm text-[#173861] outline-none focus:border-[#315d98]"/></ConfirmDialog>
    <section className="relative overflow-hidden rounded-[30px] bg-gradient-to-br from-[#173f73] via-[#315d98] to-[#79a2d0] p-7 text-white"><History className="absolute -bottom-8 -right-4 h-40 w-40 text-white/10"/><p className="relative text-xs font-bold uppercase tracking-[.18em] text-blue-100">Talento Humano</p><h1 className="relative mt-2 text-3xl font-bold">Historial laboral</h1><p className="relative mt-2 text-sm text-blue-50">Consulta procesos históricos de hojas de vida con trazabilidad de su origen.</p></section>
    <section className="grid gap-4 md:grid-cols-3"><Metric label="Personas históricas" value={totals.candidates}/><Metric label="Movimientos conservados" value={totals.movements}/><div className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><div className="flex gap-2"><ShieldCheck className="h-5 w-5 text-amber-700"/><b className="text-sm text-amber-900">Acceso restringido</b></div><p className="mt-2 text-xs text-amber-800">Incluye observaciones de selección. Solo consulta autorizada.</p></div></section>
    <div className="flex justify-end"><TrainingHint text="Esta acción elimina los datos importados del Excel histórico, no las vacantes actuales. Exige tu contraseña y no se puede deshacer; úsala solo si debes corregir una carga."><button type="button" disabled={!totals.movements||clearing} onClick={()=>setConfirmClear(true)} className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-bold text-red-700 disabled:cursor-not-allowed disabled:opacity-50">Eliminar datos importados</button></TrainingHint></div>
    <section className="rounded-3xl border border-[#dbe5f3] bg-white p-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-primary">Carga controlada</p><h2 className="mt-1 text-xl font-bold text-text">Importar archivo histórico</h2><p className="mt-1 text-sm text-textLight">Importa todas las hojas que contengan candidatos; los resúmenes se omiten.</p></div><div className="flex flex-wrap gap-3"><TrainingHint text="Elige un archivo .xlsx con el historial de hojas de vida. En modo prueba, utiliza solo datos ficticios; no subas el archivo real de personas."><label className="inline-flex cursor-pointer rounded-xl border border-primary/25 px-4 py-3 text-sm font-bold text-primary"><input type="file" accept=".xlsx" className="sr-only" onChange={e=>setFile(e.target.files?.[0]??null)}/>{file?.name??"Seleccionar Excel"}</label></TrainingHint><TrainingHint text="Revisa el nombre del archivo antes de importar. Se procesan las hojas con candidatos y se conserva el origen de cada movimiento; espera el aviso final antes de salir."><button disabled={!file||importing} onClick={()=>void upload()} className="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-bold text-white disabled:opacity-50"><FileUp size={16}/>{importing?"Importando...":"Importar historial"}</button></TrainingHint></div></div></section>
    <section className="rounded-3xl border border-[#dbe5f3] bg-white p-6">
      <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-primary">Consulta del historial</p><h2 className="mt-1 text-xl font-bold text-text">Filtrar movimientos y descargar Excel</h2></div><p className="text-xs text-textLight">El Excel respetará el período seleccionado.</p></div>
      <div className="mt-4 grid gap-3 lg:grid-cols-[minmax(200px,1fr)_180px_160px_160px_auto_auto]">
        <TrainingHint text="Escribe parte del nombre, cédula, correo o cargo. La lista se actualiza mientras escribes."><label className="relative block"><Search className="absolute left-3 top-3.5 h-4 w-4 text-textLight"/><input aria-label="Buscar historial" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}} placeholder="Nombre, cédula, correo o vacante" className="w-full rounded-xl border border-border py-3 pl-10 pr-4"/></label></TrainingHint>
        <TrainingHint text="Muestra solo los movimientos que tengan el estado seleccionado, por ejemplo Contratado o Trasladado."><select aria-label="Filtrar por estado" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}} className="w-full rounded-xl border border-border bg-white px-3 py-3 text-sm"><option value="">Todos los estados</option>{statuses.map(x=><option key={x}>{x}</option>)}</select></TrainingHint>
        <TrainingHint text="Fecha inicial del proceso que quieres consultar o incluir en el Excel."><label className="block text-xs font-semibold text-textLight">Desde<input type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1);}} className="mt-1 block w-full rounded-xl border border-border px-3 py-2.5 text-sm"/></label></TrainingHint>
        <TrainingHint text="Fecha final del proceso. No puede ser anterior a la fecha inicial."><label className="block text-xs font-semibold text-textLight">Hasta<input type="date" value={to} min={from||undefined} onChange={e=>{setTo(e.target.value);setPage(1);}} className="mt-1 block w-full rounded-xl border border-border px-3 py-2.5 text-sm"/></label></TrainingHint>
        <TrainingHint text="Vuelve a consultar la lista con los filtros actuales. La búsqueda de texto también se actualiza automáticamente." className="self-end"><button onClick={()=>void load()} className="w-full rounded-xl border border-primary/20 px-4 py-3 text-sm font-bold text-primary">Buscar</button></TrainingHint>
        <TrainingHint text="Descarga el reporte de selección con el período elegido en Desde y Hasta. Revisa las fechas antes de generar el archivo." className="self-end"><button type="button" disabled={exporting} onClick={()=>void downloadReport()} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-bold text-white shadow-sm disabled:opacity-50"><Download size={16}/>{exporting?"Generando...":"Descargar Excel"}</button></TrainingHint>
      </div>
      <div className="mt-5 overflow-x-auto">
        <table className="w-full min-w-[920px] text-left text-sm">
          <thead className="bg-[#f5f8fd] text-xs uppercase tracking-wider text-textLight"><tr><th className="p-3">Postulante</th><th className="p-3">Proceso</th><th className="p-3">Estado</th><th className="p-3">Fecha</th><th className="p-3">Origen</th><th className="p-3">Ver</th></tr></thead>
          <tbody>{items.map(x=><tr key={x.id} className="border-t border-[#edf2f8]">
            <td className="p-3"><b>{x.name}</b><p className="mt-1 text-xs text-textLight">C.C. {x.documentNumber||"No registrada"} · {x.city||"Sin ciudad"}</p></td>
            <td className="p-3"><b>{x.vacancyTitle||"Sin vacante registrada"}</b><p className="mt-1 text-xs text-textLight">{x.interviewers||"Sin entrevistador registrado"}</p></td>
            <td className="p-3"><TrainingHint text="Este color identifica el resultado registrado para este movimiento histórico. Abre la ficha para revisar observaciones y pruebas."><span className={`rounded-full border px-2.5 py-1 text-xs font-bold ${tones[x.status]||"border-slate-200 bg-slate-50"}`}>{x.status}</span></TrainingHint></td>
            <td className="p-3 text-textLight">{x.processDate?new Date(`${x.processDate}T12:00:00`).toLocaleDateString("es-CO"):"Sin fecha"}</td>
            <td className="p-3 text-xs text-textLight">{x.sourceSheet} · fila {x.sourceRow}</td>
            <td className="p-3"><TrainingHint text="Abre la ficha completa: identificación, contacto, vacante, observaciones, evaluaciones y acciones auditadas."><button aria-label={`Ver ${x.name}`} onClick={()=>setSelected(x)} title={`Ver registro: ${x.status}`} className={`inline-flex items-center gap-2 rounded-xl border px-3 py-2 font-semibold transition hover:brightness-95 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 ${tones[x.status]||"border-slate-300 bg-slate-100 text-slate-700"}`}><UserRound size={16}/>Ver</button></TrainingHint></td>
          </tr>)}</tbody>
        </table>
        {loading&&<p className="py-10 text-center text-textLight">Cargando historial...</p>}{!loading&&!items.length&&<p className="py-10 text-center text-textLight">Aún no hay registros importados o no hay coincidencias.</p>}
      </div>
    </section>
    <nav aria-label="Paginación del historial" className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-border bg-white p-4">
      <TrainingHint text="Elige cuántos registros quieres ver por página: 10 para una revisión detallada o 100 para una consulta amplia."><label className="flex items-center gap-2 text-sm">Registros por página
        <select value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1);}} className="rounded-lg border border-border px-3 py-2"><option value={10}>10</option><option value={100}>100</option></select>
      </label></TrainingHint>
      <span aria-live="polite" className="text-sm text-textLight">{pagination.total ? (pagination.page-1)*pagination.pageSize+1 : 0}–{Math.min(pagination.page*pagination.pageSize,pagination.total)} de {pagination.total}</span>
      <div className="flex items-center gap-3">
        <TrainingHint text="Regresa a la página anterior sin perder los filtros elegidos."><button disabled={loading||pagination.page<=1} onClick={()=>setPage(pagination.page-1)} className="rounded-lg border px-3 py-2 text-primary disabled:opacity-40">Anterior</button></TrainingHint>
        <span className="text-sm">Página {pagination.page} de {pagination.totalPages}</span>
        <TrainingHint text="Avanza a la siguiente página sin perder los filtros elegidos."><button disabled={loading||pagination.page>=pagination.totalPages} onClick={()=>setPage(pagination.page+1)} className="rounded-lg border px-3 py-2 text-primary disabled:opacity-40">Siguiente</button></TrainingHint>
      </div>
    </nav>
    {selected&&<ScreenDialog onClose={()=>setSelected(null)}><section className="max-h-[calc(100dvh-3rem)] w-full max-w-5xl overflow-y-auto overscroll-contain rounded-[28px] bg-[#f8fbff] p-6 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-primary">Registro histórico</p><h2 className="mt-1 text-2xl font-bold">{selected.name}</h2></div><button onClick={()=>setSelected(null)} className="rounded-xl border border-border bg-white px-4 py-2 text-sm font-bold">Cerrar</button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Detail label="Cédula" value={selected.documentNumber}/><Detail label="Contacto" value={[selected.email,selected.phone].filter(Boolean).join(" · ")}/><Detail label="Vacante" value={selected.vacancyTitle}/><Detail label="Estado" value={selected.status}/><Detail label="Origen" value={selected.source}/><Detail label="Entrevistadores" value={selected.interviewers}/><Detail label="Licencia / RUNT" value={selected.licenseCheck}/><Detail label="Referencia" value={`${selected.sourceSheet} · fila ${selected.sourceRow}`}/></div><Long label="Observaciones" value={selected.observations}/><Long label="Evaluaciones y perfil" value={selected.evaluation}/><Long label="Motivo de descarte" value={selected.discardReason}/><HistoricalRecordActions key={selected.id} id={selected.id} rawData={selected.rawData} status={selected.status} onSaved={()=>void load()}/></section></ScreenDialog>}</div>;
}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-[#dbe5f3] bg-white p-5"><p className="text-xs font-bold uppercase tracking-wider text-textLight">{label}</p><p className="mt-2 text-3xl font-bold text-primary">{value}</p></div>}
function Detail({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-border bg-white p-4"><p className="text-[11px] font-bold uppercase tracking-wider text-textLight">{label}</p><p className="mt-1 break-words text-sm font-semibold">{value||"No registrado"}</p></div>}
function Long({label,value}:{label:string;value:string}){return <div className="mt-4 rounded-xl border border-border bg-white p-4"><p className="text-[11px] font-bold uppercase tracking-wider text-textLight">{label}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{value||"No registrado"}</p></div>}
