CREATE TABLE IF NOT EXISTS sedes (
  id VARCHAR(20) NOT NULL,
  nombre VARCHAR(120) NOT NULL,
  departamento VARCHAR(80) NOT NULL,
  ciudad VARCHAR(80) NOT NULL,
  direccion VARCHAR(200) DEFAULT NULL,
  direccion_visible VARCHAR(200) DEFAULT NULL,
  administradora VARCHAR(120) DEFAULT NULL,
  telefono VARCHAR(150) DEFAULT NULL,
  foto_url MEDIUMTEXT DEFAULT NULL,
  lat DECIMAL(10,7) DEFAULT NULL,
  lng DECIMAL(10,7) DEFAULT NULL,
  estado_operativo VARCHAR(30) NOT NULL DEFAULT 'Activa',
  activa BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_sedes_departamento (departamento),
  KEY idx_sedes_ciudad (ciudad),
  KEY idx_sedes_activa (activa)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
